FROM node:16

RUN mkdir /app
WORKDIR /app

COPY ./package*.json ./
COPY ./prisma ./prisma/

COPY ./server ./server/
COPY ./utils ./utils/

RUN yarn install
RUN yarn prisma:generate
RUN yarn production:server
EXPOSE 5000