name: "Deploy Backend"
on:
  pull_request:
    branches: ["master"]
jobs:
  plan:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: Init terraform
        run: cd ${{github.workspace}}/terraform &&  terraform init

      - name: Plan ressources
        if: github.event_name == 'pull_request'
        run: cd ${{github.workspace}}/terraform && terraform plan -no-color -input=false
        continue-on-error: true
