name: "Foodle CI API test"
on:
  pull_request: {},
  jobs: 
    api_tests: 
      runs-on: ubuntu-latest
      timeout-minutes: 7
      env:
        DATABSE_URL: ${{ secrets.DATABSE_URL }}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 14.x
            cache: 'yarn'
        - run: yarn db:up
        - run: yarn 
        - run: yarn prisma:migrate:deploy
        - run: yarn test:api